### PR TITLE
fix: Fix regression(s) introduced by changes to the currentItem function in 4.3.0

### LINKED ISSUE #142: Version 4.3.0 breaks currentItem() behavior
## Description
I think version 4.3.0 broke the plugins behavior through changes in this feature. 

In the past you could call `player.playlist.currentItem()` before playback has started and receive the initial item index (defaulting to 0). 

With 4.3.0 `currentItem()` will return -1, because it tries to lookup the index by using [`playlist.currentPlaylistItemId_`](https://github.com/brightcove/videojs-playlist/blob/master/src/playlist-maker.js#L348), which is `null` until `playlistitem` has been [triggered](https://github.com/brightcove/videojs-playlist/blob/master/src/playlist-maker.js#L309).

We tried to set `playlist.currentPlaylistItemId_` to the corresponding initial value but ran into with the test cases that have been updated with this feature to handle to changed behavior of `currentItem`. 

Currently the tests only run successful because of lines like [this](https://github.com/brightcove/videojs-playlist/blob/master/test/playlist-maker.test.js#L146) that mimic the behavior when playback was started. 

I think `currentItem` should return a value >= 0 if setup worked correctly but playback hasn't started. 

## Steps to reproduce
Call `player.playlist.currentItem()`before playback has started. This will return -1 although `currentIndex_` is a valid value. 

### Expected
`currentItem()` should return a valid number when called before playback has started.

### Actual
`currentItem()` returns -1 when called before video playback has started.

### plugins
videojs-playlist 4.3.0

### PR DESCRIPTION
**Pull request by misteroneill**
Fixes #142 

This fixes a regression introduced in #115. The core issue was that we lost the old behavior of falling back to detecting the current item based on its source URL and relied exclusively on the new, internal `playlistItemId_`.

The reported issue (#142) indicated that the `currentItem()` return value before a source was set was now `-1` where previously it was `0`. This is a consequence of that change and has been fixed.

Other issues were discovered in this process. In some cases, we were leaking the internal representation of playlists. Most importantly, though, was the realization that the plugin no longer behaved correctly when a source was set from outside the playlist API (e.g. via `player.src()`).

### CODE REVIEW

File: src/play-item.js [hunk 1]
```diff
@@ -32,14 +32,20 @@ const clearTracks = (player) => {
 const playItem = (player, item) => {
   const replay = !player.paused() || player.ended();
 
-  player.trigger('beforeplaylistitem', item);
+  player.trigger('beforeplaylistitem', item.originalValue || item);
+
+  if (item.playlistItemId_) {
+    player.playlist.currentPlaylistItemId_ = item.playlistItemId_;
+  }
```
Comment (misteroneill) [inline src/play-item.js]: This needs to be set before the `player.ready` and definitely before the `playlistitem` event (moved out from `playlist-maker.js`).

File: src/playlist-maker.js [hunk 2]
```diff
@@ -248,21 +245,27 @@ export default function factory(player, initialList, initialIndex = 0) {
 
       // @todo - Simplify this to `list.slice()` for v5.
       const previousPlaylist = Array.isArray(list) ? list.slice() : null;
+      const nextPlaylist = newList.slice();
```
Comment (misteroneill) [inline src/playlist-maker.js]: We are double-`slice`ing here because below we want to pass `nextPlaylist` through the `duringplaylistchange` event. Previously, this was leaking the internal playlist abstractions during this event.

File: src/playlist-maker.js [hunk 3]
```diff
@@ -248,21 +245,27 @@ export default function factory(player, initialList, initialIndex = 0) {
...
 
       // Transform any primitive and null values in an input list to objects
       if (list.filter(item => isItemObject(item)).length !== list.length) {
         list = transformPrimitiveItems(list);
       }
 
+      // Add unique id to each playlist item. This id will be used
+      // to determine index in cases where there are more than one
+      // identical sources in the playlist.
+      generatePlaylistItemId(list);
```
Comment (misteroneill) [inline src/playlist-maker.js]: This was moved up because these IDs need to be populated _before_ we call `currentItem()` below for the `newIndex`.

File: src/playlist-maker.js [hunk 4]
```diff
@@ -304,12 +304,6 @@ export default function factory(player, initialList, initialIndex = 0) {
     }
   });
 
-  player.on('playlistitem', (event, item) => {
-    if (item && item.playlistItemId_) {
-      playlist.currentPlaylistItemId_ = item.playlistItemId_;
-    }
-  });
```
Comment (misteroneill) [inline src/playlist-maker.js]: This moved to `play-item.js`.

File: test/current-item.test.js [hunk 5]
```diff
@@ -0,0 +1,187 @@
+import QUnit from 'qunit';
```
Comment (misteroneill) [inline test/current-item.test.js]: This should be a relatively robust set of tests for the behavior of the `currentItem` function. This was the first thing I did. The workflow I took for this PR was:

1. Revert the `currentItem` changes
1. Write these tests
1. Restore the `currentItem` changes (source code, not tests)
1. Fix what broke

File: test/playlist-maker.test.js [hunk 6]
```diff
@@ -34,12 +34,6 @@ const videoList = [{
     type: 'video/mp4'
   }],
   poster: 'http://media.w3.org/2010/05/video/poster.png'
-}, {
```
Comment (misteroneill) [inline test/playlist-maker.test.js]: Most of the changes to this file are, in fact, a revert of the changes introduced in #115

File: src/playlist-maker.js [hunk 7]
```diff
@@ -344,10 +339,36 @@ export default function factory(player, initialList, initialIndex = 0) {
         playlist.player_,
         list[playlist.currentIndex_]
       );
-    } else {
-      playlist.currentIndex_ = indexInPlaylistItemIds(list, playlist.currentPlaylistItemId_);
+
+      return playlist.currentIndex_;
     }
 
+    const src = playlist.player_.currentSrc() || '';
```
Comment (misteroneill) [inline src/playlist-maker.js]: The changes below here are the meat and potatoes. See the comments for details.
