### PR TITLE
Fix: Poster hidden when item index > 0

### LINKED ISSUE #253: Only the first audio poster image is displayed (regression)
## Description
In a playlist of audio files, only, the first playlist item has its poster image displayed in the videojs player. All following items result in a black player.

## Steps to reproduce
1. Create a playlist using an `<audio>` tag with with several audio files, each having a poster image.
2. Play the second playlist item.

### Expected
The player should display the second item's poster image.

### Actual
No poster image is displayed.

## Additional Information
This bug was introduced by #243.

## Suggested resolution
Only hide poster images in video playlists. Do not hide poster images in audio playlists.

### PR DESCRIPTION
**Pull request by Essk**
## Description
Changes in #243 prevent poster "flashing" in auto-advance scenarios but introduces a new issue whereby posters are hidden if the playlist is set to an item index of > 0, whether or not it's auto-advancing. The v6 major rewrite does address this problem however it may be some time before existing integrations can be fully tested with and migrated to v6. As an interim measure, these relatively minor changes take the idea of a parameter [from v6](https://github.com/videojs/videojs-playlist/blob/350ea3b472a196c8ea27b2aabd9ef03368a59722/src/playlist-plugin.js#L109) and implement it against the v5 codebase. 

To reproduce the issue, checkout the v5.1.0 tag. Before running `npm start`, in `index.html` change the URL for the poster of the second item in the playlist from 'http://www.videojs.com/img/poster.jpg' (this is a 404) to 'http://vjs.zencdn.net/v/oceans.png'.
run `npm start`
Visit `http://localhost:9999/`
in the browser dev-tools console, enter `player.playlist.next()`. Observe that no poster is visible. Verify that `player.poster_` shows a value of `''`.

To manually test these changes, checkout this branch.
No need to update `index.html` :) 
Visit `http://localhost:9999/`
in the browser dev-tools console, enter `player.playlist.next()`. Observe that the poster is visible and `player.poster_` shows a value of `http://vjs.zencdn.net/v/oceans.png`.

We can verify that posters are still suppressed in an auto-advance setup by setting the auto-advance to a value in the UI on the test page and letting the playlist play in Chrome or Firefox. No poster flashes should be observed.

## Specific Changes proposed
* Add `suppressPoster` param  to `playItem`, `playlist.currentItem` and `playlist.next`. The parameter defaults to false.
* Set the parameter as `true` when calling `playlist.next` in `autoadvance.setup`

fixes #253 

## Requirements Checklist
- [x] Feature implemented / Bug fixed
- [ ] If necessary, more likely in a feature request than a bug fix
  - [x] Unit Tests updated or fixed
  - [ ] Docs/guides updated
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

File: src/playlist-maker.js [hunk 1]
```diff
@@ -604,18 +596,20 @@ export default function factory(player, initialList, initialIndex = 0) {
   /**
    * Plays the next item in the playlist.
    *
+   * @param {boolean} [suppressPoster]
+   *         Should the native poster be suppressed? Defaults to false.
    * @return {Object|undefined}
    *         Returns undefined and has no side effects if on last item.
    */
-  playlist.next = () => {
+  playlist.next = (suppressPoster = false) => {
```
Comment (dzianis-dashkevich) [inline src/playlist-maker.js:604]: can we use an object argument with a named prop?

Comment (misteroneill) [reply src/playlist-maker.js:604]: I'd be okay with that though it should be consistently applied in the other two cases above. I'm fine with this as-is, though. Either way works for me (especially for something that's only around for the life of 5.x).

Comment (dzianis-dashkevich) [reply src/playlist-maker.js:604]: I am okay with both approaches here,
it is just a kind / "clean code" reminder :)

Comment (Essk) [reply src/playlist-maker.js:604]: I considered this but for consistency it should be everywhere and that's a breaking change because it changes the signature of playlist.currentItem (and playItem, but I don't think that's documented as part of the api)

Also - just to note that bouncing about between branches I somehow missed off the most important change in playItem! That's been added back in with the last commit.

Comment (dzianis-dashkevich) [reply src/playlist-maker.js:604]: I got it, thank you for this clarification!

**Review by roman-bc-dev — APPROVED** [review]
